// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbtnzZakdhB6GLCRZAERM6Kla0RvgK92A',
    appId: '1:493412415077:web:02ed05c2b79376094e388c',
    messagingSenderId: '493412415077',
    projectId: 'rent-edge',
    authDomain: 'rent-edge.firebaseapp.com',
    storageBucket: 'rent-edge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0dN9rWyCMPq1WnfD-a51xosJrRmRIJg',
    appId: '1:493412415077:android:5903382f131fee1c4e388c',
    messagingSenderId: '493412415077',
    projectId: 'rent-edge',
    storageBucket: 'rent-edge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYd2Eeg2mxHMmsI8WyBLBjrtZF_nxAuEc',
    appId: '1:493412415077:ios:e116b7b4cd12177b4e388c',
    messagingSenderId: '493412415077',
    projectId: 'rent-edge',
    storageBucket: 'rent-edge.firebasestorage.app',
    iosBundleId: 'com.example.flutterTry02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYd2Eeg2mxHMmsI8WyBLBjrtZF_nxAuEc',
    appId: '1:493412415077:ios:e116b7b4cd12177b4e388c',
    messagingSenderId: '493412415077',
    projectId: 'rent-edge',
    storageBucket: 'rent-edge.firebasestorage.app',
    iosBundleId: 'com.example.flutterTry02',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbtnzZakdhB6GLCRZAERM6Kla0RvgK92A',
    appId: '1:493412415077:web:5b7e380c9f8414f04e388c',
    messagingSenderId: '493412415077',
    projectId: 'rent-edge',
    authDomain: 'rent-edge.firebaseapp.com',
    storageBucket: 'rent-edge.firebasestorage.app',
  );

}